defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      
collections:
  people_PIs:
    output: true
  people_board:
    output: true
  people_associated:
    output: true
  people_management:
    output: true
  people_visor:
    output: true  
 
      

